version: 0.2
phases:
  pre_build:
    commands:
      - echo `env`
      - echo Downloading artifact...
      - aws s3 cp s3://${ARTEFACTS_S3_NAME}/${CURRENT_PREFIX}/${VERSION_NAME}.zip ./
      - echo Unpacking artifact...
      - mkdir tmp
      - unzip -u ./${VERSION_NAME}.zip -d ./tmp
      - ls -ltr ./tmp
  build:
    commands:
      - echo Deployng the files to the ${S3_NAME} bucket
      - aws s3 cp --recursive ./tmp s3://${S3_NAME}/
      - All the files are been deployed
      - |
        if [[ "${CLOUDFRONT_ID}" != "" ]]; then
          echo Found AWS Cloudfront to create an invalidation to: ${CLOUDFRONT_ID}
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
        fi
      - The AWS Cloudfront ${CLOUDFRONT_ID} has been updated