version: 0.2

phases:
  install:
    commands:
      - yum install jq yq
  pre_build:
    commands:
      - CURRENT_NAME=""
      - CURRENT_PREFIX=""
      - DEPLOY_AFTER_BUILD="${DEPLOY_JOB_NAME}"
      - SCAN_SONAR_AFTER_BUILD="${SONAR_PROJECT_NAME}"
      - |
        if [[ ${CODEBUILD_WEBHOOK_TRIGGER} == *"tag/"* ]]; then
          CURRENT_PREFIX="${ARTEFACTS_PREFIX}"
          CURRENT_NAME=`echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed -r 's#tag/##g' | sed -r 's/[_/\*]+/-/g'`
          echo Working with the tag: ${CURRENT_NAME} in sub-directory: ${CURRENT_PREFIX}
        else
          CURRENT_PREFIX="${ARTEFACTS_TMP_PREFIX}"
          CURRENT_NAME="${CODEBUILD_SOURCE_VERSION}"
          echo Working with the tag: ${CURRENT_NAME} in sub-directory: ${CURRENT_PREFIX}
        fi
  build:
    commands:
      - echo `env`
      - yq --help
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build  -t temporary .
      - docker create -ti --name dummy temporary sh
      - docker cp dummy:${CONTAINER_WORKDIR}/${BUILD_DIRECTORY} ./
      - cd ${BUILD_DIRECTORY}; zip -r ../${CURRENT_NAME}.zip . ; cd ..
      - docker rm -f dummy
      - docker rmi temporary
      - echo Build completed on `date`
  post_build:
    commands:
      - |
        if [[ "${SCAN_SONAR_AFTER_BUILD}" != "" ]]; then
          echo Found SonarQube configuration to scan the nearly baked artefacts with ${SONAR_HOST_URL} service
          docker run --rm -e SONAR_HOST_URL="${SONAR_HOST_URL}" -e SONAR_LOGIN="${SONAR_AUTH_TOKEN}" -v "${BUILD_DIRECTORY}:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=${SONAR_PROJECT_NAME} -Dsonar.organization=${SONAR_ORGANISATION_NAME} -Dsonar.qualitygate.wait=${SONAR_WAIT_QG}
          echo The image has been scanned with ${SONAR_HOST_URL} service
        fi
      - echo Pushing the artefacts to the bucket ...
      - aws s3 cp ${CURRENT_NAME}.zip s3://${ARTEFACTS_S3_NAME}/${CURRENT_PREFIX}/${CURRENT_NAME}.zip
      - echo Checking if we have the destination s3 for the build ...
      - |
        if [[ "${DEPLOY_AFTER_BUILD}" != "" ]]; then
          echo Found the S3 bucket to deploy the nearly baked artefacts with: ${DEPLOY_JOB_NAME} job
          aws codebuild start-build --project-name ${DEPLOY_JOB_NAME} --source-version ${CODEBUILD_RESOLVED_SOURCE_VERSION} --environment-variables-override "[{\"name\":\"ARTEFACTS_S3_NAME\",\"value\":\"${ARTEFACTS_S3_NAME}\"},{\"name\":\"CURRENT_PREFIX\",\"value\":\"${CURRENT_PREFIX}\"},{\"name\":\"S3_NAME\",\"value\":\"${S3_NAME}\"},{\"name\":\"CLOUDFRONT_ID\",\"value\":\"${CLOUDFRONT_ID}\"},{\"name\":\"VERSION_NAME\",\"value\":\"${CURRENT_NAME}\"}]"
        fi