version: 0.2

phases:
  # install:
  #   commands:
  #     - wget https://github.com/mikefarah/yq/releases/download/v4.27.2/yq_linux_amd64 -O /usr/bin/yq
  #     - chmod +x /usr/bin/yq
  pre_build:
    commands:
      - CURRENT_NAME=""
      - CURRENT_PREFIX=""
      - DEPLOY_AFTER_BUILD="${DEPLOY_JOB_NAME}"
      - SCAN_SONAR_AFTER_BUILD="${SONAR_PROJECT_NAME}"
      - |
        if [[ ${CODEBUILD_WEBHOOK_TRIGGER} == *tag/* ]]; then
          CURRENT_PREFIX="${ARTEFACTS_PREFIX}"
          CURRENT_NAME=`echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed -r 's#tag/##g' | sed -r 's/[_/\*]+/-/g'`
          echo Working with the tag: ${CURRENT_NAME} in sub-directory: ${CURRENT_PREFIX}
        else
          CURRENT_PREFIX="${ARTEFACTS_TMP_PREFIX}"
          CURRENT_NAME="${CODEBUILD_SOURCE_VERSION}"
          echo Working with the tag: ${CURRENT_NAME} in sub-directory: ${CURRENT_PREFIX}
        fi
  build:
    commands:
      - echo `env`
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build  -t temporary .
      - docker create -ti --name dummy temporary sh
      - docker cp dummy:${CONTAINER_WORKDIR}/${BUILD_DIRECTORY} ./
      - cd ${BUILD_DIRECTORY}; zip -r ../${CURRENT_NAME}.zip . ; cd ..
      - docker rm -f dummy
      - docker rmi temporary
      - echo Build completed on `date`
  post_build:
    commands:
      - |
        if [[ "${SCAN_SONAR_AFTER_BUILD}" != "" ]]; then
          echo Found SonarQube configuration to scan the nearly baked artefacts with ${SONAR_HOST_URL} service
          docker run --rm -e SONAR_HOST_URL="${SONAR_HOST_URL}" -e SONAR_LOGIN="${SONAR_AUTH_TOKEN}" -v "${BUILD_DIRECTORY}:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=${SONAR_PROJECT_NAME} -Dsonar.organization=${SONAR_ORGANISATION_NAME} -Dsonar.qualitygate.wait=${SONAR_WAIT_QG}
          echo The image has been scanned with ${SONAR_HOST_URL} service
        fi
      - echo Pushing the artefacts to the bucket ...
      - aws s3 cp ${CURRENT_NAME}.zip s3://${ARTEFACTS_S3_NAME}/${CURRENT_PREFIX}/${CURRENT_NAME}.zip
      - echo Checking if we have the destination s3 according to the deployment matrix
      - S3_NAME=`jq -r '.[] | select(.source_head_ref as $ref | env.CODEBUILD_WEBHOOK_HEAD_REF | startswith($ref)) | .s3_name' <<< $DEPLOY_MATRIX_JSON`
      - CLOUDFRONT_ID=`jq -r '.[] | select(.source_head_ref as $ref | env.CODEBUILD_WEBHOOK_HEAD_REF | startswith($ref)) | .cloudfront_id' <<< $DEPLOY_MATRIX_JSON`
      - CURRENT_ENV = `jq -r 'with_entries(select(.value.source_head_ref as $ref | "refs/tags/" | startswith($ref)) | . )' <<< $DEPLOY_MATRIX_JSON | jq -r 'keys[0]'`
      - echo The deployment parameters are ${S3_NAME} ${CLOUDFRONT_ID} ${DEPLOY_AFTER_BUILD}
      - |
        if [[ "${DEPLOY_AFTER_BUILD}" != "" && "${S3_NAME}" != "" ]]; then
          echo Found the S3 bucket to deploy the nearly baked artefacts with: ${DEPLOY_JOB_NAME} job
          aws codebuild start-build --project-name ${DEPLOY_JOB_NAME} --source-version ${CODEBUILD_RESOLVED_SOURCE_VERSION} --environment-variables-override "[{\"name\":\"ARTEFACTS_S3_NAME\",\"value\":\"${ARTEFACTS_S3_NAME}\"},{\"name\":\"CURRENT_PREFIX\",\"value\":\"${CURRENT_PREFIX}\"},{\"name\":\"S3_NAME\",\"value\":\"${S3_NAME}\"},{\"name\":\"CLOUDFRONT_ID\",\"value\":\"${CLOUDFRONT_ID}\"},{\"name\":\"VERSION_NAME\",\"value\":\"${CURRENT_NAME}\"},{\"name\":\"CURRENT_ENV\",\"value\":\"${CURRENT_ENV}\"}]"
        else
          echo The destination for the matrix deploy is not found. Please check the configuration
        fi