name: Build Push

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
      
jobs:
  build_push:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the Docker image 
      if: "!contains(github.ref, 'pull')"
      run: docker build . --file Dockerfile --tag bora23/test-dborovets:$GITHUB_REF_NAME-$GITHUB_SHA
    - name: Build the Docker image on Pull request
      if: contains(github.ref, 'pull')
      run: docker build . --file Dockerfile --tag bora23/test-dborovets:$GITHUB_RUN_ID
    - name: Docker Push
      if: "!contains(github.ref, 'pull')"
      run: docker push bora23/test-dborovets:$GITHUB_REF_NAME-$GITHUB_SHA
