name: Build Push

on:
  push:
    branches: 
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:

  build_push:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    env:
      Container_Name: bora23/test-dborovets
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $Container_Name:$GITHUB_REF_NAME-$GITHUB_SHA
    - name: Docker Push
      run: docker push $Container_Name:$GITHUB_REF_NAME-$GITHUB_SHA
