name: Deploy

on:
  workflow_run:
    workflows: Docker Image CI
    branches: master
    types: completed

jobs:

  test:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Install wget and yq
      run: wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod a+x /usr/local/bin/yq
    - name: Setup SSH key  
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
        sudo chmod 600 ~/.ssh/private.key
      shell: bash
    - name: Test
      run: |
       git clone -b master git@github.com:ait-dborovets/argo-test.git
       
 
      
      
