name: Deploy

on:
  workflow_run:
    workflows: Docker Image CI
    branches: master
    types: completed

jobs:

  test:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Install wget and yq
      run: wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod a+x /usr/local/bin/yq
    - name: Setup SSH key  
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
      shell: bash
    - name: Change version and deploy
      run: |
       git config --global user.name test
       git config --global user.email test@ait.com
       git clone -b master git@github.com:ait-dborovets/argo-test.git
       cd argo-test/react
       yq e -i '.image.tag = "'$GITHUB_REF_NAME_$GITHUB_SHA'"' dev-values.yaml
       cat dev-values.yaml
       git commit -am "update image tag" && git push origin master
       
       
 
      
      
