name: Deploy Helm

on:
  workflow_run:
    workflows: Build Push
    branches:
      - dev
      - master
    types: completed

jobs:

  test:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Set env vars (dev)
      if: endsWith(github.ref, '/dev')
      run: |
        echo "Values_Name=dev-values.yaml" >> $GITHUB_ENV
    - name: Set env vars (prod)
      if: endsWith(github.ref, '/master')
      run: |
        echo "Values_Name=prod-values.yaml" >> $GITHUB_ENV
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Install kubectl
      run: |
       aws ecr get-login-password --region eu-central-1 | helm registry login --username AWS --password-stdin 935818769908.dkr.ecr.eu-central-1.amazonaws.com
       helm upgrade -i -n dev new-dev-react oci://935818769908.dkr.ecr.eu-central-1.amazonaws.com/react --version 0.1.0 --set=image.tag="test1"
