name: Deploy Helm

on:
  workflow_run:
    workflows: Build Push
    branches:
      - dev
      - master
    types: completed

jobs:

  test:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    env:
      AWS_REGION: eu-central-1
      aws-account: 935818769908
    steps:
    - name: Set env vars (dev)
      if: endsWith(github.ref, '/dev')
      run: |
        echo "Values_Name=dev-values.yaml" >> $GITHUB_ENV
    - name: Set env vars (prod)
      if: endsWith(github.ref, '/master')
      run: |
        echo "Values_Name=prod-values.yaml" >> $GITHUB_ENV
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $AWS_REGION
    - name: Update App Tag
      env:
        cluster-name: test
        git-email: test@ait.com
      run: |
       aws ecr get-login-password --region $AWS_REGION | helm registry login --username AWS --password-stdin $aws-account.dkr.ecr.$AWS_REGION.amazonaws.com
       aws eks update-kubeconfig --region $AWS_REGION --name dborovets-playground1-STAGE-EKS
       helm upgrade -i -n dev new-dev-react oci://$aws-account.dkr.ecr.$AWS_REGION.amazonaws.com/react --version 0.1.0 --set=image.tag=$GITHUB_REF_NAME-$GITHUB_SHA
