name: Deploy Helm

on:
  workflow_run:
    workflows: Build Push
    branches:
      - dev
      - master
    types: completed

jobs:

  test:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    env:
      AWS_REGION: eu-central-1
      AWS_ACCOUNT: 935818769908
    steps:
    - name: Set env vars (dev)
      if: endsWith(github.ref, '/dev')
      run: |
        echo "ENV=dev" >> $GITHUB_ENV
    - name: Set env vars (prod)
      if: endsWith(github.ref, '/master')
      run: |
        echo "ENV=prod" >> $GITHUB_ENV
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $AWS_REGION
    - name: Update App Tag
      env:
        CLUSTER_NAME: dborovets-playground1-STAGE-EKS
        APP_NAME: react
        CHART_VERSION: 0.1.0
      run: |
       aws ecr get-login-password --region $AWS_REGION | helm registry login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
       aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
       helm upgrade -i -n $ENV new-$ENV-$APP_NAME oci://$AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME --version $CHART_VERSION --set=image.tag=$GITHUB_REF_NAME-$GITHUB_SHA
