name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_push:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag bora23/test-dborovets:$(date +%s)
    - name: Docker Push
      run: docker push bora23/test-dborovets:$(date +%s)
