name: My deploy workflow

on:
  workflow_run:
    workflows: Docker Image CI
    branches: master
    types: completed

jobs:

  test:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Test
      run: echo 123
